"""`pm schedule` — register read-only commands so they happen without you.

Nothing that writes to Jira (or publishes) is allowed on a timer. The job
list lives in `~/.pm/schedule.json`. On Windows the companion PowerShell
script registers Task Scheduler entries; elsewhere a crontab snippet is
written next to the job list.
"""

import json
import os
import re
import subprocess
import sys

from core import paths


SAFE = {
    "today": [],
    "report": [],
    "metrics": ["--weeks", "8"],
    "lint": [],
    "standup": [],
    "doctor": [],
    "brief": None,   # needs --for at add time
    "ready": [],
    "workstreams": ["check"],
    "products": ["check"],
}

UNSAFE = {"do", "refine", "triage", "inbox", "note", "publish", "review"}


def _store(cfg):
    path = paths.schedule_path(cfg)
    if not os.path.exists(path):
        return {"jobs": []}
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except (ValueError, OSError):
        return {"jobs": []}
    if not isinstance(data, dict) or "jobs" not in data:
        return {"jobs": []}
    return data


def _save(cfg, store):
    path = paths.schedule_path(cfg)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(store, fh, indent=2)


def parse_when(at=None, weekly=None):
    """Return {kind, days, time} from --at HH:MM or --weekly fri@16:00."""
    if weekly:
        match = re.fullmatch(r"([a-z]{3})@(\d{1,2}:\d{2})",
                             str(weekly).strip().lower())
        if not match:
            raise ValueError("Weekly trigger looks like fri@16:00.")
        day, time = match.group(1), match.group(2)
        names = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
        if day not in names:
            raise ValueError(f"Unknown weekday {day!r}.")
        return {"kind": "weekly", "days": [day], "time": time}
    if at:
        match = re.fullmatch(r"(\d{1,2}:\d{2})", str(at).strip())
        if not match:
            raise ValueError("Daily trigger looks like 08:30.")
        return {"kind": "weekdays", "days": ["mon", "tue", "wed", "thu", "fri"],
                "time": match.group(1)}
    raise ValueError("Need --at HH:MM or --weekly fri@16:00.")


def cron_line(job, pm="pm"):
    hour, minute = job["time"].split(":")
    args = " ".join(job.get("args") or [])
    cmd = f"{pm} {job['command']}" + (f" {args}" if args else "")
    if job["kind"] == "weekdays":
        dow = "1-5"
    else:
        names = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
        # cron: 0 = Sunday. Our list is mon-first for weekdays; map explicitly.
        cron_map = {"sun": "0", "mon": "1", "tue": "2", "wed": "3",
                    "thu": "4", "fri": "5", "sat": "6"}
        dow = ",".join(cron_map[d] for d in job["days"])
    return f"{int(minute)} {int(hour)} * * {dow} {cmd}"


def _write_cron(cfg, store):
    path = os.path.join(paths.local_dir(cfg), "schedule.cron")
    lines = ["# Generated by `pm schedule`. Install with: crontab schedule.cron",
             ""]
    for job in store.get("jobs") or []:
        lines.append(f"# {job['name']}")
        lines.append(cron_line(job))
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def _register_windows(job):
    script = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                          "scripts", "register-pm-task.ps1")
    if not os.path.exists(script):
        return False
    args = [job["command"]] + (job.get("args") or [])
    try:
        subprocess.run(
            ["powershell", "-NoProfile", "-File", script,
             "-Name", job["name"],
             "-Command", " ".join(args),
             "-Kind", job["kind"],
             "-Time", job["time"],
             "-Days", ",".join(job["days"])],
            check=False, capture_output=True, text=True, timeout=30)
        return True
    except (OSError, subprocess.SubprocessError):
        return False


def _add(cfg, args):
    command = getattr(args, "target", None)
    if not command:
        sys.exit("Which command? e.g.  pm schedule add today --at 08:30")
    name = command.lower()
    if name in UNSAFE or name not in SAFE:
        sys.exit(f"`pm {command}` is not safe unattended. "
                 f"Schedule one of: {', '.join(sorted(SAFE))}.")
    extra = []
    if name == "brief":
        audience = getattr(args, "for_audience", None)
        if not audience:
            sys.exit("`pm schedule add brief` needs --for \"Audience\".")
        extra = ["--for", audience]
    elif getattr(args, "for_audience", None):
        extra = ["--for", args.for_audience]
    if getattr(args, "product", None):
        extra += ["--product", args.product]
    if getattr(args, "workstream", None):
        extra += ["--workstream", args.workstream]
    try:
        when = parse_when(at=getattr(args, "at", None),
                          weekly=getattr(args, "weekly", None))
    except ValueError as err:
        sys.exit(str(err))
    job = {
        "name": name,
        "command": name,
        "args": extra,
        **when,
    }
    store = _store(cfg)
    store["jobs"] = [j for j in store["jobs"] if j.get("name") != name]
    store["jobs"].append(job)
    _save(cfg, store)
    cron = _write_cron(cfg, store)
    registered = False
    if os.name == "nt":
        registered = _register_windows(job)
    print(f"Scheduled {name} ({when['kind']} at {when['time']}).")
    if registered:
        print("Registered with Task Scheduler.")
    else:
        print(f"Crontab snippet written to {cron}.")
        print("Nothing that writes to Jira will run on this timer.")


def _list(cfg, args):
    store = _store(cfg)
    jobs = store.get("jobs") or []
    if not jobs:
        print("No scheduled commands. Add one with:")
        print("  pm schedule add today --at 08:30")
        print("  pm schedule add report --weekly fri@16:00")
        return
    print("SCHEDULE")
    print("")
    for job in jobs:
        days = ",".join(job.get("days") or [])
        extra = " ".join(job.get("args") or [])
        print(f"  {job['name']:<12} {job['kind']:<8} {job['time']}  "
              f"{days}   pm {job['command']}"
              + (f" {extra}" if extra else ""))


def _remove(cfg, args):
    name = getattr(args, "target", None)
    if not name:
        sys.exit("Which job? e.g.  pm schedule remove today")
    store = _store(cfg)
    before = len(store["jobs"])
    store["jobs"] = [j for j in store["jobs"]
                     if j.get("name") != name.lower()]
    if len(store["jobs"]) == before:
        sys.exit(f"No scheduled job named {name}.")
    _save(cfg, store)
    _write_cron(cfg, store)
    print(f"Removed {name}.")


def run(cfg, args):
    action = getattr(args, "action", "list") or "list"
    if action == "list":
        _list(cfg, args)
    elif action == "add":
        _add(cfg, args)
    elif action == "remove":
        _remove(cfg, args)
    else:
        sys.exit(f"Unknown schedule action {action}. Try: list, add, remove.")
